<?php require TEMPLATES . '/includes/header.phtml' ?>

<h1>Adicionar produto:</h1>

<form action="<?php echo HOME; ?>?url=/produto/create" method="post"
    enctype="multipart/form-data"
>
    <div>
        <label for="name">Nome: </label>
        <input type="text" id="name" name="name" placeholder="Nome do produto:">
    </div>

    <div>
        <label for="description">Descrição: </label>
        <textarea id="description" name="description" placeholder="Sobre...">
        </textarea>
    </div>

    <div>
        <label for="price">Preço: </label>
        <input type="text" id="price" name="price" placeholder="R$00,00">
    </div>

    <div>
        <label for="quantity">Quantidade em estoque: </label>
        <input type="number" id="quantity" name="quantity" value="1">
    </div>

    <div>
        <label for="status">Status: </label>
        <select id="status" name="status">
            <option value="1">Ativo</option>
            <option value="0">Inativo</option>
        </select>
    </div>

    <div>
        <label for="pictures">Foto(s) do produto: </label>
        <input type="file" name="pictures[]" id="pictures" multiple>
    </div>

    <button>Salvar</button>
</form>

<?php require TEMPLATES . '/includes/footer.phtml' ?>